applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'app_departamento'

urlpatterns = [
    path('add_departamento/', views.Add_departamento.as_view(), name='add_departamento'),
    path('departamentos/', views.Lista_departamentos.as_view(), name="departamentos")

]

applications/employee/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "employee_app"
urlpatterns = [
    path('template/', views.CheckView.as_view(), name="template"),
    path('inform/<pk>/', views.HourList.as_view(), name="inform"),
]

applications/personal/urls.py
from django.urls import path
from . import views

app_name = 'app_personal'

urlpatterns = [
    
    path('', views.IndexView.as_view(), name="home"),
    path('logout/', views.logout_view, name="logout"),
    path('list_employed/', views.List_employed.as_view(), name='lista_empleados'),
    path('list_employed_off/', views.List_employed_off.as_view(), name='lista_empleados_off'),
    path('add_empleado/', views.CrearEmpleado.as_view(), name='add_empleado'),
    path('detalles/<pk>/', views.detalle_personal.as_view(),name='detalle_personal'),
    path('departamento_personal/<departamento>', views.Personal_departamento.as_view(), name='departamento_personal'),
    path('administrar/', views.Administrar.as_view(), name='administrar'),
    path('administrar_empleados/', views.Administrar_empleados.as_view(), name='administrar_empleados'),
    path('actualizar/<pk>', views.Actualizar.as_view(), name='actualizar'),
    path('eliminar/<pk>', views.Eliminar_personal.as_view(),name='eliminar'),
    path('cargo/', views.Add_Cargo.as_view(),name='cargo'),
    path('add_habilidad/', views.Add_Habilidad.as_view(),name='habilidad'),
]

attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.employee.urls')),
    path('', include('applications.personal.urls')),
    path('', include('applications.departamento.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/personal/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField
from model_utils.models import TimeStampedModel
from .managers import EmployeeManager

# Create your models here.

class Habilidades(models.Model):
    habilidades = models.CharField('Habilidades', max_length=50, blank=True)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'
    def __str__(self):
        return self.habilidades


class Cargo(models.Model):
    cargo = models.CharField('Cargo', max_length=50)
    descripcion = RichTextField('Descripcion del Cargo')
    class Meta:
        verbose_name = 'Cargo'
        verbose_name_plural = 'Cargos'
    def __str__(self):
        return self.cargo


class Personal(TimeStampedModel):
    DOCUMENT_CHOISES = [
        ('DNI', 'DNI',),
        ('CI', 'CI',),
        ('PASAPORTE', 'PASAPORTE',),
        ('CARNET DE EXTRANGERIA', 'CARNET DE EXTRANJERIA',),
    ]
   
    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellido', max_length=50)
    card = models.CharField("Tarjeta", max_length=40)
    fecha_nacimiento = models.DateField("Fecha de nacimiento")
    t_documento = models.CharField('Tipo de Documento',max_length=30, choices=DOCUMENT_CHOISES, default='DNI')
    n_documento = models.IntegerField('Numero de documento')
    foto = models.ImageField('Foto', upload_to='foto/')
    n_telefonico = models.IntegerField('Numero de telefono')
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    fecha_ingreso = models.DateField('Fecha de ingreso')
    habilidades = models.ManyToManyField(Habilidades)
    dotacion = RichTextField("Dotacion de uniformes", blank=True)
    aportes =  RichTextField('Aportes', blank=True)
    deficiencias = RichTextField('Deficiencias',blank=True)
    recomendaciones = RichTextField('Recomendaciones', blank=True)
    n_faltas = models.IntegerField('Numero de Faltas',blank=True, default=0)
    falta_des = RichTextField('Descripcion de faltas', blank=True)
    activo = models.BooleanField("Activo", default=True)
    curriculum = models.FileField('Curriculum', upload_to='curriculums/')
    objects = objects = EmployeeManager()
    
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

    def __str__(self) -> str:
        return str(self.id) + ' - ' + self. first_name + ' - ' + self.last_name

applications/personal/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import *


class Empleado_form(forms.ModelForm):
    
    class Meta:
        model = Personal
        fields = ('__all__')
       
        widgets = {
            'habilidades' : forms.CheckboxSelectMultiple(),
            'first_name' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese nombre...'
                }
            ),
            'first_name' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese nombre...'
                }
            ),
            'last_name' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese apellido...'
                }
            ),
            'fecha_nacimiento' : forms.TextInput(
                attrs={
                    'placeholder':'Fecha de nacimiento...'
                }
            ),
            'n_documento' : forms.TextInput(
                attrs={
                    'placeholder':'N° de documento...'
                }
            ),
            'n_telefonico' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese telefono...'
                }
            ),
            'fecha_ingreso' : forms.TextInput(
                attrs={
                    'placeholder':'Fecha de ingreso...'
                }
            ),
            'n_faltas' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese N° de faltas...'
                }
            )
            }

class HabilidadesForm(forms.ModelForm):
    
    class Meta:
        model = Habilidades
        fields = ('__all__')
       
        widgets = {
            'habilidades' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese nueva habilidad...'
                }
            )
            }

class CargoForm(forms.ModelForm):
    
    class Meta:
        model = Cargo
        fields = ('__all__')
       
        widgets = {
            'cargo' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese nombre del cargo...'
                }
            )
            }


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nombre de usuario'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}))

applications/personal/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    TemplateView,
    FormView
)
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib import messages
from .forms import *
from .models import Personal, Cargo, Habilidades
from django.urls import reverse_lazy

# Inicio de sesion
class IndexView(FormView):
    template_name = 'home/index.html'
    form_class = LoginForm
    success_url = "/"

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            form.add_error(None, 'Nombre de usuario o contraseña incorrectos.')
            return self.form_invalid(form)
        
# cerrar sesion
def logout_view(request):
    logout(request)
    return redirect("app_personal:home")
        
# Lista de Empleados
class List_employed(LoginRequiredMixin, ListView):
    template_name = 'personal/list_employed.html'
    context_object_name ='personal'
    paginate_by = 5
    login_url = reverse_lazy('app_personal:home')

    def get_queryset(self):
        trabajo = self.request.GET.get('trabajador',"")
        lista = Personal.objects.filter(
        first_name__contains = trabajo,
        activo = True
        )
    
        return lista

# Lista de Empleados Deshabilitados
class List_employed_off(LoginRequiredMixin,ListView):
    template_name = 'personal/list_employed_off.html'
    context_object_name ='personas'
    paginate_by = 5
    login_url = reverse_lazy('app_personal:home')

    def get_queryset(self):
        trabajo = self.request.GET.get('trabajador',"")
        lista = Personal.objects.filter(
        first_name__contains = trabajo,
        activo = False
        )
    
        return lista

# Detalles de empleados
class detalle_personal(LoginRequiredMixin, DetailView):
    template_name = "personal/detalles.html"
    context_object_name = "empleado"
    model = Personal
    login_url = reverse_lazy('app_personal:home')

# Personal por departamentos
class Personal_departamento(LoginRequiredMixin, ListView):
    template_name = "personal/personal_departamento.html"
    context_object_name = "personal"
    login_url = reverse_lazy('app_personal:home')
    
    def get_queryset(self):
        trabajador = self.request.GET.get('trabajador',"")
        departamento = self.kwargs['departamento']
        lista = Personal.objects.filter(
            departamento_id = departamento,
            first_name__contains = trabajador
        )

        return lista

# vista de administracion de departamentos, cargos y habilidades
class Administrar(LoginRequiredMixin,TemplateView):
    template_name = "personal/administrar.html"
    login_url = reverse_lazy('app_personal:home')

# vista previa para editar o inhabilitar empleados
class Administrar_empleados(LoginRequiredMixin, ListView):
    template_name = 'personal/administrar_empleados.html'
    context_object_name ='personas'
    paginate_by = 7
    login_url = reverse_lazy('app_personal:home')

    def get_queryset(self):
        trabajo = self.request.GET.get('trabajo',"")
        lista = Personal.objects.filter(
        first_name__contains = trabajo
        )
    
        return lista

# Cargar empleados nuevos al sistema
class CrearEmpleado(LoginRequiredMixin,CreateView):
    template_name = 'personal/crear_empleado.html'
    model = Personal
    form_class = Empleado_form
    success_url =reverse_lazy('app_personal:add_empleado')
    login_url = reverse_lazy('app_personal:home')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Registro de empleado exitoso")
        return response

# Actualizar empleados
class Actualizar(LoginRequiredMixin, UpdateView):
    template_name = 'personal/update.html'
    model = Personal
    form_class = Empleado_form
    login_url = reverse_lazy('app_personal:home')
    success_url =reverse_lazy('app_personal:lista_empleados')
    def form_valid(self, form):
        messages.success(self.request, "Actualizacion exitosa Exitoso")
        return super().form_valid(form)

# Eliminar empleados
class Eliminar_personal(LoginRequiredMixin, DeleteView):
    model = Personal
    template_name = "personal/eliminar_personal.html"
    success_url =reverse_lazy('app_personal:lista_empleados')
    login_url = reverse_lazy('app_personal:home')
    
# Agregar cargos
class Add_Cargo(LoginRequiredMixin, CreateView):
    model = Cargo
    template_name = "personal/add_cargo.html"
    form_class = CargoForm
    success_url =reverse_lazy('app_personal:cargo')
    login_url = reverse_lazy('app_personal:home')
    
    def form_valid(self, form):
        messages.success(self.request, "Registro Exitoso")
        return super().form_valid(form)

# Agregar habilidades
class Add_Habilidad(LoginRequiredMixin, CreateView):
    model = Habilidades
    template_name = "personal/add_habilidad.html"
    form_class = HabilidadesForm
    success_url =reverse_lazy('app_personal:habilidad')
    login_url = reverse_lazy('app_personal:home')

    def form_valid(self, form):
        messages.success(self.request, "Registro Exitoso")
        return super().form_valid(form)

templates/personal/add_cargo.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Crear nuevo Cargo
{% endblock title %}

{% block content %}
    <div class="grid-container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div>
            <form class="callout" method = 'POST'> {% csrf_token %}
                <h3 class="h1-cabecera2">Crear nuevo Cargo</h3>
                <hr>
                {{form.as_p}}
                <button class="button warning" type="submit">Guardar</button>
            </form>
        </div>
    </div>
{% endblock content %}

    

templates/personal/add_habilidad.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Crear nueva habilidad
{% endblock title %}

{% block content %}
    <div class="grid-container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div>
            <form class="callout" method = 'POST'> {% csrf_token %}
                <h3 class="h1-cabecera2">Crear nueva habilidad</h3>
                <hr>
                {{form.as_p}}
                <button class="button warning" type="submit">Guardar</button>
            </form>
        </div>
    </div>
{% endblock content %}

    

templates/personal/administrar.html
{%extends 'layout.html'%}
{% load static %}

{% block title %}
    Administrador de registros
{% endblock title %}
{% block content %}
   <div class="grid-container">
        
    <h1 class="h1-cabecera"> Administrador</h1>
    <hr>
        <div class="expanded button-group align-center">
            <a href="{% url 'app_departamento:add_departamento' %}" class="secondary button">Cargar Departamento</a>
        </div>
        <div class="expanded button-group align-center">
            <a href="{% url 'app_personal:cargo' %}" class="warning button">Cargar Cargo</a>
        </div>
        <div class="expanded button-group align-center">
            <a href="{% url 'app_personal:habilidad' %}" class="alert button">Cargar Habilidad</a>
        </div>
        <div class="expanded button-group align-center">
            <a href="{% url 'app_personal:administrar_empleados' %}" class=" button">Editar Empleados</a>
        </div>
   </div>
{% endblock content %}

 

templates/personal/administrar_empleados.html
{%extends 'layout.html'%}
{% load static %}

{% block title %}
    Administrador de registros
{% endblock title %}
{% block content %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell h1-cabecera2"> Lista de empleados</h1>
                <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                    <div class="cell large-7">
                        <input type="text" id='trabajo' name="trabajo" placeholder="buscar empleados">
                    </div>
                    <div class="cell large-2">
                        <button class="submit success button" type='submit'>Buscar</button>
                    </div>
                </form>
            <div class="cell">
                <table  class="hover">
                    <thead>
                      <tr>
                        <th width="150">Nombre</th>
                        <th width="150">Apellido</th>
                        <th width="150">Departamento</th>
                        <th width="150">Cargo</th>
                        <th width="75">Accion</th>
                        <th width="75"></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for lista in personas %}
                            <tr>             
                                <td>{{lista.first_name}}</td>
                                <td>{{lista.last_name}}</td>
                                <td>{{lista.departamento}}</td>
                                <td>{{lista.cargo}}</td> 
                                <td><a class="button success"  href="{% url 'app_personal:actualizar' lista.id %}">Editar</a></td>
                                <td><a class="button alert"  href="{% url 'app_personal:eliminar' lista.id %}">eliminar</a></td>                    
                            </tr>
                        {%endfor%}
                    </tbody>
                  </table>
            </div>
            {% if is_paginated %}
                <div class="cell">
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            {% if page_obj.has_previous  %}
                            <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">atras</a></li>
                            {% endif %}
                            {% for pagina in paginator.page_range %}
                                {%if pagina == page_obj.number%}
                                    <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                                {% else %}        
                                    <li><a href="?page={{pagina}}" aria-label="Pagina {{pagina}}">{{pagina}}</a></li>
                                {%endif%}
                            {% endfor %}
                            {% if page_obj.has_next  %}
                                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">siguiente</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            {% endif %}
        </div>  
{% endblock content %}

 

templates/personal/crear_empleado.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Crear registro de empleado
{% endblock title %}

{% block content %}
  {% include 'includes/form_empleados.html' %}
{% endblock content %}

templates/personal/detalles.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Empleado: {{empleado.first_name}}
{% endblock title %}

{% block content %}
    <div class="grid-container fondo">
        <h1 class="h1-cabecera2">Detalles del empleado</h1>
        <div class="media-object">
            <div class="media-object-section">
              <div class="thumbnail carnet" >
                <img src="{{empleado.foto.url}}">
              </div>
            </div>
            <div class="media-object-section">
              <h4>{{empleado.first_name}} {{empleado.last_name}}</h4>
              <p class="fecha">Fecha de Nacimiento: {{empleado.fecha_nacimiento}}</p>
              <hr>
              <table>
                <thead>
                    <tr>
                        <th width="150">Departamento</th>
                        <th width="150">Cargo</th>
                        <th width="180">Fecha de Ingreso</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{empleado.departamento}}</td>
                        <td>{{empleado.cargo}}</td>
                        <td>{{empleado.fecha_ingreso}}</td>
                    </tr>
                </tbody>
                <thead>
                    <tr>
                        <th width="150">Habilidades</th>
                        <th width="150">Numero de Amonestaciones</th>
                        <th width="150">Descripcion de Amonestaciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <ul>
                            {% for habilidad in empleado.habilidades.all %}
                                <li>{{habilidad}}</li>
                            {% endfor %}
                            </ul>
                        </td>
                        <td>{{empleado.n_faltas}}</td>
                        <td>{{empleado.falta_des|safe}}</td>
                    </tr>
                </tbody>
            </table>
            <hr>
            <h4>Descargar resumen Curricular</h4>
            <a href="{{empleado.curriculum.url}}" class="button">Descarga "Aqui"</a>
            <a href="{%url 'employee_app:inform' empleado.id %}" class="button">Ver control de Asistencias</a>
            <hr>
            <h4>Dotacion de Uniforme</h4>
              <p>{{empleado.dotacion|safe}}</p>
            <hr>
            <h4>Aportes del empleado</h4>
              <p>{{empleado.aportes|safe}}</p>
            <hr>
            <h4>Deficiencias del empleado</h4>
            <p>{{empleado.deficiencias|safe}}</p>
            <hr>
            <h4>Recomendaciones para el empleado</h4>
            <p>{{empleado.recomendaciones|safe}}</p>
            <hr>
            </div>
          </div>
    </div>
{% endblock content %}

templates/personal/eliminar_personal.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Confirmacion
{% endblock title %}

{% block content %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell large-12 callout secundary">
            <h2 class="cell">Confirmar que desea eliminar a:</h2>
            <p class="cell eliminar_nombre">{{object.first_name}} {{object.last_name}} </p>
            <form class="cell" method="POST">{% csrf_token %}
                <button class="button alert" type="submit">Eliminar</button>
                <a class="button delete boton_cancelar" href="{% url 'app_personal:administrar' %}">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/personal/list_employed.html
{%extends 'layout.html'%}
{% load static %}

{% block title %}
    Lista de empleados
{% endblock title %}
{% block content %}
    {% include 'includes/lista_empleados.html' %}     
{% endblock content %}

templates/personal/list_employed_off.html
{%extends 'layout.html'%}
{% load static %}

{% block title %}
    Lista de empleados
{% endblock title %}
{% block content %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell h1-cabecera2"> Lista de empleados</h1>
                <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                    <div class="cell large-7">
                        <input type="text" id='trabajador' name="trabajador" placeholder="buscar empleados">
                    </div>
                    <div class="cell large-2">
                        <button class="submit success button" type='submit'>Buscar</button>
                    </div>
                </form>
            <div class="cell">
                <table  class="hover">
                    <thead>
                      <tr>
                        <th width="150">Nombre</th>
                        <th width="150">Apellido</th>
                        <th width="150">Antiguo Departamento</th>
                        <th width="150">Antiguo Cargo</th>
                        <th width="200">Accion</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for lista in personas %}
                            <tr>           
                                <td>{{lista.first_name}}</td>
                                <td>{{lista.last_name}}</td>
                                <td>{{lista.departamento}}</td>
                                <td>{{lista.cargo}}</td>   
                                <td>
                                    <a class="button warning"  href="{% url 'app_personal:detalle_personal' lista.id %}">Ver</a>
                                    <a class="button success"  href="{% url 'app_personal:actualizar' lista.id %}">Editar</a>
                                    <a class="button alert"  href="{% url 'app_personal:eliminar' lista.id %}">eliminar</a>

                                </td>                     
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
            {% if is_paginated %}
                <div class="cell">
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            {% if page_obj.has_previous  %}
                            <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">atras</a></li>
                            {% endif %}
                            {% for pagina in paginator.page_range %}
                                {%if pagina == page_obj.number%}
                                    <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                                {% else %}        
                                    <li><a href="?page={{pagina}}" aria-label="Pagina {{pagina}}">{{pagina}}</a></li>
                                {%endif%}
                            {% endfor %}
                            {% if page_obj.has_next  %}
                                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">siguiente</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            {% endif %}
        </div>
    </div>   
{% endblock content %}

 

templates/personal/personal_departamento.html
{% extends 'layout.html' %}
{% include 'includes/personal_departamento.html' %}

{% block title %}
    {{Departamento}}
{% endblock title %}

{% block content %}
    {% include 'includes/lista_empleados.html' %}
{% endblock content %}

templates/personal/proceso_exitoso.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Proceso exitoso
{% endblock title %}

{% block content %}
<div class="grid-container ">
    <div class= "grid-x">
    <h1 class="cell guardado-exitoso  align-center">REGISTRO EXITOSO</h1>
    </div>
</div>
{% endblock content %}

templates/personal/update.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Actualizar datos de empleado
{% endblock title %}

{% block content %}
{% include 'includes/form_empleados.html' %}
{% endblock content %}