applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'app_departamento'

urlpatterns = [
    path('add_departamento/', views.Add_departamento.as_view(), name='add_departamento'),
    path('departamentos/', views.Lista_departamentos.as_view(), name="departamentos")

]

applications/personal/urls.py
from django.urls import path
from . import views

app_name = 'app_personal'

urlpatterns = [
    
    path('', views.IndexView.as_view(), name="home"),
    path('logout/', views.logout_view, name="logout"),
    path('list_employed/', views.List_employed.as_view(), name='lista_empleados'),
    path('list_employed_off/', views.List_employed_off.as_view(), name='lista_empleados_off'),
    path('add_empleado/', views.CrearEmpleado.as_view(), name='add_empleado'),
    path('detalles/<pk>/', views.detalle_personal.as_view(),name='detalle_personal'),
    path('departamento_personal/<departamento>', views.Personal_departamento.as_view(), name='departamento_personal'),
    path('administrar/', views.Administrar.as_view(), name='administrar'),
    path('administrar_empleados/', views.Administrar_empleados.as_view(), name='administrar_empleados'),
    path('actualizar/<pk>', views.Actualizar.as_view(), name='actualizar'),
    path('eliminar/<pk>', views.Eliminar_personal.as_view(),name='eliminar'),
    path('cargo/', views.Add_Cargo.as_view(),name='cargo'),
    path('add_habilidad/', views.Add_Habilidad.as_view(),name='habilidad'),
]

attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.employee.urls')),
    path('', include('applications.personal.urls')),
    path('', include('applications.departamento.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/form_empleados.html
<div class="grid-container">
    <h1 class= "cell h1-cabecera2">Registro de empleado</h1>
    <div class="cell align-center">
      {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
      <form class="callout grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="medium-6 cell">
            <label>Nombre
              {{form.first_name}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Apellido
              {{form.last_name}}
            </label>
        </div>
        <div class="medium-6 cell">
          <label>Tarjeta
            {{form.card}}
          </label>
        </div>
        <div class="medium-6 cell">
            <label>Fecha de Nacimiento
              {{form.fecha_nacimiento}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Tipo de Documento
              {{form.t_documento}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Numero de Documento
              {{form.n_documento}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Cargar Foto
              {{form.foto}}
            </label>
        </div>
        <div class="medium-6 cell">
          <label>N° Telefonico
            {{form.n_telefonico}}
          </label>
        </div>
        <div class="medium-6 cell">
            <label>Departamento
              {{form.departamento}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Cargo
              {{form.cargo}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Fecha de Ingreso
              {{form.fecha_ingreso}}
            </label>
        </div>
        <div class="medium-8 cell">
            <label>Habilidades
              {{form.habilidades}}
            </label>
        </div>
        <div class="medium-6 cell">
          <label>Dotacion y Uniformes</label>
          {{form.dotacion}}
      </div>
        <div class="medium-6 cell">
            <label>Aportes</label>
              {{form.aportes}}
        </div>
        <div class="medium-6 cell">
            <label>Deficiencias</label>
              {{form.deficiencias}}
        </div>
        <div class="medium-6 cell">
            <label>Recomendaciones</label>
              {{form.recomendaciones}}
        </div>
        <div class="medium-8 cell">
            <label>Numero de Amonestaciones
              {{form.n_faltas}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Detalles de Amonestaciones</label>
              {{form.falta_des}}
        </div>
        <div class="medium-8 cell">
            <label>Cargar Curriculum</label>
            {{form.curriculum}}
        </div>
        <div class="medium-6 cell">
            <label>Activo</label>
              {{form.activo}}
        </div>
          <div class="cell">
            <button class="button warning" type="submit">Guardar</button>
       </div>
      </form>
    </div>
</div>

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">
          <a class ="nombre_header" href="{% url 'app_personal:home' %}">Home</a>
        </li>
        <li class="menu-text">
          <a href="{% url 'app_personal:lista_empleados'%}">Lista</a>
        </li>
        <li class="menu-text">
            <a href="{%url 'app_departamento:departamentos'%}">Departamentos</a>
        </li>
        <li class="menu-text">
          <a href="{% url 'app_personal:administrar' %}">Administrar</a>
        </li>
        <li class="menu-text">
          <a href="{%url 'app_personal:lista_empleados_off'%}">Antiguos empleados</a>
        </li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><a href="{% url 'app_personal:add_empleado' %}" class="button">Registrar Empleado</a></li>
        {% if user.is_authenticated %}<li><a href="{% url 'app_personal:logout' %}" class="cell hollow button alert">Cerrar sesión</a></li>{% endif %}
      </ul>
    </div>
  </div>

  
<!-- menu vertical

-->

templates/includes/header_.html
{% load static %}
<div class="grid-x top-bar">
  <div class="cell navegacion" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <ul class="orbit-container">
      <li class="is-active orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image cabe" src="{% static 'img/cabecera_.png' %}"  alt="Space">
          <figcaption class="orbit-caption">Sistemas de control RammerBot.</figcaption>
        </figure>
      <li class="orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/cabecera.png' %}"alt="Space">
          <figcaption class="orbit-caption">Conectamos tu empresa con el futuro</figcaption>
        </figure>
      </li>
    </ul>
  </div>    
  
</div>

templates/includes/lista_empleados.html
<div class="grid-container">
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    <div class="grid-x">
        <h1 class="h1-cabecera2 cell"> Lista de empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id='trabajador' name="trabajador" placeholder="buscar empleados">
            </div>
            <div class="cell large-2">
                <button class="submit success button" type='submit'>Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table  class="hover">
                <thead>
                  <tr>
                    <th width="150">Nombre</th>
                    <th width="150">Apellido</th>
                    <th width="150">Departamento</th>
                    <th width="150">Cargo</th>
                    <th width="150">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    {% for lista in personal %}
                        <tr>              
                            <td>{{lista.first_name}}</td>
                            <td>{{lista.last_name}}</td>
                            <td>{{lista.departamento}}</td>
                            <td>{{lista.cargo}}</td>
                            <td><a class="button warning"  href="{% url 'app_personal:detalle_personal' lista.id %}">Ver</a></td>                    
                        </tr>
                    {%endfor%}
                </tbody>
              </table>
        </div>
        {% if is_paginated %}
            <div class="cell">
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous  %}
                        <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">atras</a></li>
                        {% endif %}
                        {% for pagina in paginator.page_range %}
                            {%if pagina == page_obj.number%}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                            {% else %}        
                                <li><a href="?page={{pagina}}" aria-label="Pagina {{pagina}}">{{pagina}}</a></li>
                            {%endif%}
                        {% endfor %}
                        {% if page_obj.has_next  %}
                            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">siguiente</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>    

templates/includes/menu_vertical.html
<div class="grid-x">
    <div class="cell small-2">
        <div class="cell">
            <h4 class="cell usuario"> Bienvenido al Control de Horario</h4>
            <hr>
        </div>

    </div>
    <div class="cell large-9 centro">