applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'app_departamento'

urlpatterns = [
    path('add_departamento/', views.Add_departamento.as_view(), name='add_departamento'),
    path('departamentos/', views.Lista_departamentos.as_view(), name="departamentos")

]

applications/personal/urls.py
from django.urls import path
from . import views

app_name = 'app_personal'

urlpatterns = [
    
    path('', views.IndexView.as_view(), name="home"),
    path('logout/', views.logout_view, name="logout"),
    path('list_employed/', views.List_employed.as_view(), name='lista_empleados'),
    path('list_employed_off/', views.List_employed_off.as_view(), name='lista_empleados_off'),
    path('add_empleado/', views.CrearEmpleado.as_view(), name='add_empleado'),
    path('detalles/<pk>/', views.detalle_personal.as_view(),name='detalle_personal'),
    path('departamento_personal/<departamento>', views.Personal_departamento.as_view(), name='departamento_personal'),
    path('administrar/', views.Administrar.as_view(), name='administrar'),
    path('administrar_empleados/', views.Administrar_empleados.as_view(), name='administrar_empleados'),
    path('actualizar/<pk>', views.Actualizar.as_view(), name='actualizar'),
    path('eliminar/<pk>', views.Eliminar_personal.as_view(),name='eliminar'),
    path('cargo/', views.Add_Cargo.as_view(),name='cargo'),
    path('add_habilidad/', views.Add_Habilidad.as_view(),name='habilidad'),
]

attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.employee.urls')),
    path('', include('applications.personal.urls')),
    path('', include('applications.departamento.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Departamento', max_length=50)
    short_name = models.CharField('Nombre corto', max_length=20, unique=True)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
    
    def __str__(self):
        return self.short_name

applications/departamento/forms.py
from django import forms
from .models import Departamento

class DepartamentoForm(forms.ModelForm):
    
    class Meta:
        model = Departamento
        fields = ('__all__')
       
        widgets = {
            'name' : forms.TextInput(
                attrs={
                    'placeholder':'Ingrese nuevo departamento...'
                }
            ),
            'short_name' : forms.TextInput(
                attrs={
                    'placeholder':'Nombre referencial...'
                }
            )
            }

applications/departamento/views.py
from django.forms.models import BaseModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, FormView, CreateView
from .forms import *
from applications.personal.models import Personal
from .models import Departamento
from django.urls import reverse_lazy


# Create your views here.

class Add_departamento(LoginRequiredMixin, CreateView):
    model = Departamento
    template_name = "departamento/add_departamento.html"
    form_class = DepartamentoForm
    success_url =reverse_lazy('app_departamento:add_departamento')
    login_url = reverse_lazy('app_personal:home')

    def form_valid(self, form: BaseModelForm):
        messages.success(self.request, "Registro Exitoso")
        return super().form_valid(form)

   

class Lista_departamentos(LoginRequiredMixin, ListView):
    model = Departamento
    template_name = "departamento/lista_departamentos.html"
    context_object_name = "departamentos"
    login_url = reverse_lazy('app_personal:home')

templates/departamento/add_departamento.html
{% extends 'layout.html' %}
{% include 'includes/header.html' %}

{% block title %}
    Crear nuevo departamento
{% endblock title %}

{% block content %}
    <div class="grid-container">
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <div>
            <form class="callout" method = 'POST'> {% csrf_token %}
                <h3 class="h1-cabecera2">Crear nuevo departamento</h3>
                {{form.as_p}}
                <button class="button warning" type="submit">Guardar</button>
            </form>
        </div>
    </div>
{% endblock content %}

    

templates/departamento/lista_departamentos.html
{% extends 'layout.html' %}
{% include 'includes/header.html'%}

{% block title %}
    Departamentos
{% endblock title %}
{% block content %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell h1-cabecera2">Departamentos de la empresa</h1>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th>
                                Nombre del departamento
                            </th>
                            <th>
                                Referencia
                            </th>
                            <th>
                                Accion
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for departamento in departamentos %}
                            <tr>
                                <td width='200'>
                                    {{departamento.name}}
                                </td>
                                <td width='200'>
                                    {{departamento.short_name}}
                                </td>
                                <td width='200'>
                                    <a class="button warning"  href="{% url 'app_personal:departamento_personal' departamento.id %}">Ver Empleados</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}